### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/summerofhacks.github.io#1]
@matthewhh has thrown down some shapes - as usual, totally awesome.

1.
![summer of hacks-02](https://cloud.githubusercontent.com/assets/51385/7164192/8ec184de-e396-11e4-8193-a4ac0555f9d7.png)

2.
![summer of hacks-01](https://cloud.githubusercontent.com/assets/51385/7164196/986d7cea-e396-11e4-939a-a7863d36ccd8.png)

3.
![summer of hacks-03](https://cloud.githubusercontent.com/assets/51385/7164204/a0190fd6-e396-11e4-8b73-2339558a1a3e.png)

4.
![summer of hacks-06](https://cloud.githubusercontent.com/assets/51385/7164209/a5ad3198-e396-11e4-821f-e3871b9aeda1.png)

5.
![summer of hacks-04](https://cloud.githubusercontent.com/assets/51385/7164214/aef62b2e-e396-11e4-87e7-51a28d84e11e.png)

6.
![summer of hacks-05](https://cloud.githubusercontent.com/assets/51385/7164217/b54c2fd2-e396-11e4-97ca-210a3e6f1670.png)

**Comment by benfoxall** [comment]
I'm quite into `1` - bit of a link to JSOxford

**Comment by spikeheap** [comment]
I'm **totally** into `1`, and :clap: @matthewhh for pulling these together for us!

**Comment by benfoxall** [comment]
also, svg export - https://gist.github.com/benfoxall/7d1ae66bea4aaf18d3fc

**Comment by spikeheap** [comment]
Sorted :+1:
