### ISSUE TITLE
Menu items

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/summerofhacks.github.io#7]
I've been modifying the site to get more content in.  I'm thinking of a menu system along the lines of:

![screen shot 2015-05-05 at 14 08 10](https://cloud.githubusercontent.com/assets/51385/7473104/619c8cfc-f330-11e4-8e0b-d17c3449aefd.png)

I'm thinking 
- **Info** - what it's about, locations, code of conduct
- **Events** - list of all events, links out to meetup
- **Sponsors** - list sponsors & how to get in touch about sending us stuff
- **Contact** - organisers, and how to get in touch

1) am I missing anything?
2) do we have any sponsor logos yet?

**Comment by spikeheap** [comment]
Sounds good @benfoxall, I like it.

I think it's better to have the event summaries on the front page as it is atm so the key info is there to get people interested, but maybe have them link off to the event pages you're creating, if that's the plan.

We also need the code of conduct on there. The markdown is already in the repo, it just needs linking.

Also, it's not clear what the difference is between "info" and "events". If I want to find out the venue for an event, which one would I look at? It might make more sense to just drop the 'info' and append that content to each event page (pulled in from partials of course). What do you think?

Could we start PR-ing SoH like we do jsoxford?

**Comment by AverageMarcus** [comment]
How about specifically having a "Where" menu item?

**Comment by benfoxall** [comment]
It's all on the same page at the moment - got a bit of a trendy parallax thing going on as you scroll down.

I was thinking of "info" as being general intro text, with a map of the two locations (more to resolve #6 rather than for people to looking for directions).  "events" would be the list of events for people to choose which ones to come along to.

Sure, I'll raise this in PR when it's more together - I've got to park it just now; hopefully pick it up some evening this week.

Do we have a list of sponsors for that section?

**Comment by benfoxall** [comment]
Maybe a "where" section would work - or I was playing round with having "Oxford 2015" on it somewhere

**Comment by spikeheap** [comment]
:+1:, all on one page makes sense, I misunderstood that screenshot as going off to pages and having only the logo.

Maybe we should add "Oxford 2015" under the SoH as part of the logo? Or something.

Sponsors so far:
- Haybrook IT
- White October
- [Espruino](http://www.espruino.com/) (NodeBots) 
- [New Bamboo](https://www.new-bamboo.co.uk/) (RailsBridge)
- [Cucumber Pro](https://cucumber.pro/) (RailsBridge) -- they also get points for their URL.
- ... more to come
