### ISSUE TITLE
Hosting 3s latency

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/summerofhacks.github.io#8]
The first request 302s and the next one takes a while http://www.webpagetest.org/result/150505_TB_NXX/

This is because of githubs attack mitigation strategy, from github support:

> You can avoid the 302 redirects by either putting your page on a subdomain and using a CNAME record pointing to username.github.io, or using an ALIAS record with an apex domain (not supported by all DNS hosts).
> 
> If your DNS host does support ALIAS records, you can find instructions here:
> 
> https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/#configuring-an-alias-or-aname-record-with-your-dns-provider
> 
> If you'd like to move to a subdomain, you can find instructions here:
> 
> https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/

---

Another alternative is to use a different hosting altogether, it's set up to deploy [to s3](http://summerofhacks.io.s3-website-eu-west-1.amazonaws.com/), we could point at that with cloudfront or cloudflare.

**Comment by spikeheap** [comment]
Yeah finding a DNS provider that supports ALIAS records isn't much fun, and would cost to transfer.

I'll +1 moving to S3.
